"""
Django settings for IMX project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Final

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Final = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-r8+u&iawflm^0y6kh477cm@xdcdh6%6vry75iib6#-frp72j@h'
try:
    SECRET_KEY = os.environ["SECRET_KEY"]
except KeyError:
    with open(BASE_DIR / "LOCAL_DEV_ENV" / "SECRET_KEY.txt") as f:
        SECRET_KEY = f.read().replace("\n", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Codes to add new apps to INSTALLED_APPS automatically
exclude = [".git", ".github", "IMX", "locale", "LOCAL_DEV_ENV", "media", "static"]
apps = [x.name for x in BASE_DIR.glob("*/") if x.name not in exclude]
INSTALLED_APPS += apps

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "IMX.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "IMX.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom Authentication
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth
#
# Substitutiing a custom User model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = "users.User"

# Globalization (i18n/l10n)
# https://docs.djangoproject.com/en/5.2/ref/settings/#globalization-i18n-l10n
#
# Internationalization (i18n)
# https://docs.djangoproject.com/en/5.2/ref/settings/#internationalization-i18n
#
# LANGUAGES
# https://docs.djangoproject.com/en/5.2/ref/settings/#languages

LANGUAGES = [
    ("ko", _("한국어")),
    ("en", _("영어")),
]

# LOCALE_PATHS
# https://docs.djangoproject.com/en/5.2/ref/settings/#locale-paths

LOCALE_PATHS = [
    "locale/",
]

# File uploads
# https://docs.djangoproject.com/en/5.2/ref/settings/#file-uploads
#
# MEDIA_ROOT
# https://docs.djangoproject.com/en/5.2/ref/settings/#media-root

MEDIA_ROOT = "media/"
